general {
  hide_cursor = true
  grace = 0
}

background {
  monitor = eDP-1
  path = $HOME/.config/hypr/Wallpapers/bg.png
  blur_passes = 0
  color = rgb(10,10,10)
}

label {
  monitor =
  text = $TIME
  color = rgb(220,220,220)
  font_size = 72
  font_family = JetBrainsMono Nerd Font
  position = 0, -150
  halign = center
  valign = center
}

input-field {
  monitor =
  size = 300, 60
  outline_thickness = 4
  dots_size = 0.2
  dots_spacing = 0.2
  dots_center = true
  outer_color = rgb(130,170,255)
  inner_color = rgb(30,30,30)
  font_color = rgb(230,230,230)
  fade_on_empty = false
  placeholder_text = <span foreground="##aaaaaa"><i>Enter password…</i></span>
  hide_input = false
  check_color = rgb(130,170,255)
  fail_color  = rgb(255,80,80)
  fail_text   = <i>Wrong password</i>
  capslock_color = rgb(255,200,0)
  position = 0, 60
  halign = center
  valign = center
}